name: Verify ability to build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Setup Node.js

      - run: npm install
        name: Install dependencies

      - run: npm run build
        name: Verify ability to build
